docs: add quickstart and quick links
builders-club/vscode-twitch-themer pull request #159
Opened 2020-11-13 15:50 UTC by ToeFrog

Added a quickstart section to the README file as well as quick links to jump to specific sections in the file.

2020-11-13 23:01 UTC, cmjchrisjones requested changes
Hey @ToeFrog, can you also change the target branch from `main` to `vNext` too please?

2020-11-14 00:17 UTC, ToeFrog commented on README.md
> +Connect Twitch Themer to Twitch from the [Command Pallete](#command-palette) (Ctrl + Shift + P)
@cmjchrisjones Updated and fixed the type. Also changed the target branch.

2020-11-14 01:05 UTC, cmjchrisjones commented
@ToeFrog seems to be a lot more changes in this PR now than there was before, guessing that your original branch was based of `main` rather than `vNext`?

2020-11-14 12:27 UTC, ToeFrog commented
I've created a new branch off vNext and made the changes there. I will submit a new PR and close this one. Sorry for the confusion. In the future I will make sure to target the vNext branch rather than main.

2020-11-14 12:27 UTC, closed without merging